spring:
  mysqldatasource:
    url: jdbc:mysql://localhost:3306/erudit?useSSL=false&allowPublicKeyRetrieval=true
    username: erudit
    password: Erud1t_P@ss$645

  data:
    mongodb:
      username: erudit
      password: erudit_#211
      database: erudit
      port: 27018

#P@ssw0rd&654

fileDirectory: "/opt/tomcat/files"

#springdoc:
#  swagger-ui:
#    path: /index.html