spring:
  mysqldatasource:
    url: jdbc:mysql://localhost:3306/erudit?useSSL=false
    username: erudit
    password: Erud1t_P@ss$645

#P@ssw0rd&654

fileDirectory: "/opt/tomcat/files"

#springdoc:
#  swagger-ui:
#    path: /index.html