spring:
  profiles:
    active: @activeProfile@
  main:
    banner-mode: off

#server:
#  servlet:
#    context-path: /api/v1

logging:
  level:
    web: DEBUG
    org:
      springframework:
        jdbc.core: TRACE
        web:
          HttpLogging: TRACE
          servlet.mvc.method.annotation:
            HttpEntityMethodProcessor: TRACE
            RequestResponseBodyMethodProcessor: TRACE
#        security: TRACE