spring:
  mysqldatasource:
    url: jdbc:mysql://localhost:3306/erudit?useSSL=false
    username: root
    password: root

fileDirectory: "D:/Github/erudit_isit/files"

#springdoc:
#  swagger-ui:
#    path: /index.html